"""initial migration

Revision ID: c47f739b6e0c
Revises: 
Create Date: 2026-06-14 18:58:21.332847

"""
from alembic import op
import sqlalchemy as sa
from app.extensions import INET, JSONB, ARRAY


# revision identifiers, used by Alembic.
revision = 'c47f739b6e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attack_type', sa.Enum('PORT_SCAN', 'BRUTE_FORCE', 'DDOS', 'TRAFFIC_ANOMALY', 'ML_ANOMALY', name='attack_type_enum', create_constraint=True), nullable=False),
    sa.Column('source_ip', INET(), nullable=False),
    sa.Column('target_ip', INET(), nullable=True),
    sa.Column('target_port', sa.Integer(), nullable=True),
    sa.Column('evidence', JSONB(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MONITORING', 'RESOLVED', 'FALSE_POSITIVE', name='attack_status_enum', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_events_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index('ix_attack_events_source_ip_first_seen', ['source_ip', 'first_seen'], unique=False)
        batch_op.create_index('ix_attack_events_type_status', ['attack_type', 'status'], unique=False)

    op.create_table('ip_reputation',
    sa.Column('ip_address', INET(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('categories', ARRAY(sa.Text()), nullable=True),
    sa.Column('sources', JSONB(), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('asn', sa.String(length=20), nullable=True),
    sa.Column('as_name', sa.String(length=255), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_table('packet_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('src_ip', INET(), nullable=False),
    sa.Column('dst_ip', INET(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('packet_size', sa.Integer(), nullable=False),
    sa.Column('flags', sa.String(length=20), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packet_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packet_logs_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index('ix_packet_logs_dst_ip_captured_at', ['dst_ip', 'captured_at'], unique=False)
        batch_op.create_index('ix_packet_logs_ports', ['src_port', 'dst_port'], unique=False)
        batch_op.create_index('ix_packet_logs_protocol_captured_at', ['protocol', 'captured_at'], unique=False)
        batch_op.create_index('ix_packet_logs_src_ip_captured_at', ['src_ip', 'captured_at'], unique=False)

    op.create_table('protocol_stats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('byte_count', sa.BigInteger(), nullable=False),
    sa.Column('unique_src_ips', sa.Integer(), nullable=False),
    sa.Column('unique_dst_ips', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_stats', schema=None) as batch_op:
        batch_op.create_index('ix_protocol_stats_window', ['protocol', 'window_start'], unique=False)

    op.create_table('system_stats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('packets_per_second', sa.Float(), nullable=False),
    sa.Column('bytes_per_second', sa.Float(), nullable=False),
    sa.Column('active_connections', sa.Integer(), nullable=False),
    sa.Column('alerts_count', sa.Integer(), nullable=False),
    sa.Column('blocked_ips_count', sa.Integer(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('db_connections_active', sa.Integer(), nullable=True),
    sa.Column('packet_drop_rate', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_stats', schema=None) as batch_op:
        batch_op.create_index('ix_system_stats_recorded_at', ['recorded_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('old_value', JSONB(), nullable=True),
    sa.Column('new_value', JSONB(), nullable=True),
    sa.Column('ip_address', INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('blacklist',
    sa.Column('ip_address', INET(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_table('brute_force_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attack_event_id', sa.UUID(), nullable=False),
    sa.Column('targeted_service', sa.String(length=50), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('attempt_rate', sa.Float(), nullable=True),
    sa.Column('usernames_tried', ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['attack_event_id'], ['attack_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brute_force_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brute_force_details_attack_event_id'), ['attack_event_id'], unique=True)

    op.create_table('ddos_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attack_event_id', sa.UUID(), nullable=False),
    sa.Column('attack_vector', sa.String(length=50), nullable=True),
    sa.Column('packets_per_second', sa.Float(), nullable=True),
    sa.Column('bytes_per_second', sa.Float(), nullable=True),
    sa.Column('contributing_ips', ARRAY(INET()), nullable=True),
    sa.Column('amplification_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attack_event_id'], ['attack_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ddos_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ddos_details_attack_event_id'), ['attack_event_id'], unique=True)

    op.create_table('ip_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', INET(), nullable=False),
    sa.Column('block_type', sa.Enum('AUTO', 'MANUAL', name='block_type_enum', create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('attack_event_id', sa.UUID(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('firewall_rule_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['attack_event_id'], ['attack_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_blocks_ip_address'), ['ip_address'], unique=True)

    op.create_table('ml_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('packet_feature_vector', ARRAY(sa.Float()), nullable=True),
    sa.Column('prediction', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attack_event_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['attack_event_id'], ['attack_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_predictions_attack_event_id'), ['attack_event_id'], unique=False)
        batch_op.create_index('ix_ml_predictions_predicted_at', ['predicted_at'], unique=False)

    op.create_table('port_scan_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attack_event_id', sa.UUID(), nullable=False),
    sa.Column('scanned_ports', ARRAY(sa.Integer()), nullable=True),
    sa.Column('scan_rate', sa.Float(), nullable=True),
    sa.Column('scan_pattern', sa.String(length=50), nullable=True),
    sa.Column('technique', sa.Enum('SYN', 'CONNECT', 'UDP', 'FIN', 'XMAS', 'NULL', name='scan_technique_enum', create_constraint=True), nullable=True),
    sa.ForeignKeyConstraint(['attack_event_id'], ['attack_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('port_scan_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_scan_details_attack_event_id'), ['attack_event_id'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('threat_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attack_event_id', sa.UUID(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('rate_modifier', sa.Integer(), nullable=False),
    sa.Column('duration_modifier', sa.Integer(), nullable=False),
    sa.Column('recurrence_modifier', sa.Integer(), nullable=False),
    sa.Column('ip_reputation_modifier', sa.Integer(), nullable=False),
    sa.Column('ml_confidence_modifier', sa.Integer(), nullable=False),
    sa.Column('blacklist_modifier', sa.Integer(), nullable=False),
    sa.Column('whitelist_override', sa.Boolean(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity_level_enum', create_constraint=True), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attack_event_id'], ['attack_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_scores_attack_event_id'), ['attack_event_id'], unique=True)

    op.create_table('whitelist',
    sa.Column('ip_address', INET(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ip_address')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attack_event_id', sa.UUID(), nullable=False),
    sa.Column('threat_score_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', name='alert_status_enum', create_constraint=True), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attack_event_id'], ['attack_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_score_id'], ['threat_scores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_attack_event_id'), ['attack_event_id'], unique=False)
        batch_op.create_index('ix_alerts_severity_status_created', ['severity', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_threat_score_id'), ['threat_score_id'], unique=False)

    op.create_table('alert_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_comments_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_comments_user_id'), ['user_id'], unique=False)

    op.create_table('email_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'FAILED', 'PERMANENTLY_FAILED', name='email_delivery_status_enum', create_constraint=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_notifications_alert_id'), ['alert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_notifications_alert_id'))

    op.drop_table('email_notifications')
    with op.batch_alter_table('alert_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_comments_alert_id'))

    op.drop_table('alert_comments')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_threat_score_id'))
        batch_op.drop_index('ix_alerts_severity_status_created')
        batch_op.drop_index(batch_op.f('ix_alerts_attack_event_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_assigned_to'))

    op.drop_table('alerts')
    op.drop_table('whitelist')
    with op.batch_alter_table('threat_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_scores_attack_event_id'))

    op.drop_table('threat_scores')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('port_scan_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_scan_details_attack_event_id'))

    op.drop_table('port_scan_details')
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_ml_predictions_predicted_at')
        batch_op.drop_index(batch_op.f('ix_ml_predictions_attack_event_id'))

    op.drop_table('ml_predictions')
    with op.batch_alter_table('ip_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_blocks_ip_address'))

    op.drop_table('ip_blocks')
    with op.batch_alter_table('ddos_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ddos_details_attack_event_id'))

    op.drop_table('ddos_details')
    with op.batch_alter_table('brute_force_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brute_force_details_attack_event_id'))

    op.drop_table('brute_force_details')
    op.drop_table('blacklist')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index('ix_audit_logs_user_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_system_stats_recorded_at')

    op.drop_table('system_stats')
    with op.batch_alter_table('protocol_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_protocol_stats_window')

    op.drop_table('protocol_stats')
    with op.batch_alter_table('packet_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_packet_logs_src_ip_captured_at')
        batch_op.drop_index('ix_packet_logs_protocol_captured_at')
        batch_op.drop_index('ix_packet_logs_ports')
        batch_op.drop_index('ix_packet_logs_dst_ip_captured_at')
        batch_op.drop_index(batch_op.f('ix_packet_logs_captured_at'))

    op.drop_table('packet_logs')
    op.drop_table('ip_reputation')
    with op.batch_alter_table('attack_events', schema=None) as batch_op:
        batch_op.drop_index('ix_attack_events_type_status')
        batch_op.drop_index('ix_attack_events_source_ip_first_seen')
        batch_op.drop_index(batch_op.f('ix_attack_events_source_ip'))

    op.drop_table('attack_events')
    # ### end Alembic commands ###
